-- Employee Management System schema for Supabase/PostgreSQL.
-- Run this once in the Supabase SQL Editor for the project configured in .env.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  department text not null default 'IT',
  email text not null unique,
  password text not null,
  initials text,
  status text not null default 'Working',
  role text not null default 'Employee',
  created_at timestamptz not null default now()
);

create table if not exists public.leave_balances (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  total_days numeric(6, 2) not null default 24,
  used_days numeric(6, 2) not null default 0,
  constraint leave_balances_days_check check (total_days >= 0 and used_days >= 0)
);

create table if not exists public.daily_work_entries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  entry_date date not null,
  work_description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_work_entries_user_date_unique unique (user_id, entry_date)
);

create table if not exists public.leave_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  leave_type text not null,
  start_date date not null,
  end_date date not null,
  days_count numeric(6, 2) not null default 1,
  day_of_week text,
  start_time time,
  end_time time,
  special_session text,
  is_recurring boolean not null default false,
  status text not null default 'Pending',
  reason text not null default '',
  created_at timestamptz not null default now(),
  constraint leave_requests_date_order check (end_date >= start_date),
  constraint leave_requests_days_check check (days_count > 0)
);

create table if not exists public.auth_otps (
  email text not null,
  type text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  last_sent_at timestamptz not null default now(),
  primary key (email, type),
  constraint auth_otps_type_check check (type in ('register', 'reset-password'))
);

create table if not exists public.email_events (
  id bigint generated by default as identity primary key,
  recipient text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  constraint email_events_status_check check (status in ('pending', 'processing', 'sent', 'failed')),
  constraint email_events_attempts_check check (attempts >= 0)
);

create index if not exists email_events_queue_idx
  on public.email_events (status, next_attempt_at, created_at);

create or replace function public.claim_email_events(batch_size integer default 20)
returns setof public.email_events
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  update public.email_events
  set status = 'processing',
      attempts = attempts + 1,
      locked_at = now(),
      last_error = null
  where id in (
    select id
    from public.email_events
    where status in ('pending', 'failed')
      and next_attempt_at <= now()
      and attempts < 5
    order by created_at
    for update skip locked
    limit greatest(1, least(batch_size, 100))
  )
  returning *;
end;
$$;

create or replace function public.record_leave_decision(p_leave_id bigint, p_status text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  leave_row public.leave_requests;
  user_row public.users;
begin
  if p_status not in ('Approved', 'Rejected') then
    raise exception 'Invalid leave decision';
  end if;

  select * into leave_row
  from public.leave_requests
  where id = p_leave_id and status = 'Pending'
  for update;

  if not found then
    raise exception 'Pending leave request not found';
  end if;

  select * into user_row
  from public.users
  where id = leave_row.user_id;

  if not found then
    raise exception 'Employee not found';
  end if;

  update public.leave_requests
  set status = p_status
  where id = p_leave_id;

  insert into public.email_events (recipient, event_type, payload)
  values (
    user_row.email,
    case when p_status = 'Approved' then 'leave_approved' else 'leave_rejected' end,
    jsonb_build_object(
      'employeeName', user_row.name,
      'leaveType', leave_row.leave_type,
      'startDate', leave_row.start_date,
      'endDate', leave_row.end_date,
      'daysCount', leave_row.days_count
    )
  );

  return jsonb_build_object('id', p_leave_id, 'status', p_status);
end;
$$;

revoke execute on function public.claim_email_events(integer) from public, anon, authenticated;
grant execute on function public.claim_email_events(integer) to service_role;

revoke execute on function public.record_leave_decision(bigint, text) from public, anon, authenticated;
grant execute on function public.record_leave_decision(bigint, text) to service_role;

create index if not exists leave_requests_user_created_idx
  on public.leave_requests (user_id, created_at desc);

create index if not exists leave_requests_active_dates_idx
  on public.leave_requests (status, start_date, end_date);

create index if not exists daily_work_entries_date_idx
  on public.daily_work_entries (entry_date desc);

alter table public.users enable row level security;
alter table public.leave_balances enable row level security;
alter table public.daily_work_entries enable row level security;
alter table public.leave_requests enable row level security;
alter table public.auth_otps enable row level security;
alter table public.email_events enable row level security;
