-- Employee Management System schema for Supabase/PostgreSQL.
-- Run this once in the Supabase SQL Editor for the project configured in .env.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  department text not null default 'IT',
  email text not null unique,
  password text not null,
  initials text,
  status text not null default 'Working',
  role text not null default 'Employee',
  created_at timestamptz not null default now()
);

create table if not exists public.leave_balances (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  total_days numeric(6, 2) not null default 24,
  used_days numeric(6, 2) not null default 0,
  constraint leave_balances_days_check check (total_days >= 0 and used_days >= 0)
);

create table if not exists public.daily_work_entries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  entry_date date not null,
  work_description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_work_entries_user_date_unique unique (user_id, entry_date)
);

create table if not exists public.leave_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  leave_type text not null,
  start_date date not null,
  end_date date not null,
  days_count numeric(6, 2) not null default 1,
  day_of_week text,
  start_time time,
  end_time time,
  special_session text,
  is_recurring boolean not null default false,
  status text not null default 'Pending',
  reason text not null default '',
  created_at timestamptz not null default now(),
  constraint leave_requests_date_order check (end_date >= start_date),
  constraint leave_requests_days_check check (days_count > 0)
);

create table if not exists public.auth_otps (
  email text not null,
  type text not null,
  code_hash text not null,
  expires_at timestamptz not null,
  last_sent_at timestamptz not null default now(),
  primary key (email, type),
  constraint auth_otps_type_check check (type in ('register', 'reset-password'))
);

create index if not exists leave_requests_user_created_idx
  on public.leave_requests (user_id, created_at desc);

create index if not exists leave_requests_active_dates_idx
  on public.leave_requests (status, start_date, end_date);

create index if not exists daily_work_entries_date_idx
  on public.daily_work_entries (entry_date desc);

alter table public.users enable row level security;
alter table public.leave_balances enable row level security;
alter table public.daily_work_entries enable row level security;
alter table public.leave_requests enable row level security;
alter table public.auth_otps enable row level security;
